### ISSUE TITLE
MSVS 2015 build file generation issue

### ISSUE THREAD

**Issue by Oletus** [Kangz/GLDriverBugs#1]
I tried building with CMake 3.6 and MSVS 2015 on Windows 10 as follows:

mkdir build
cd build
cmake ..

Open DriverBugs.sln in Visual Studio 2015 update 2.

When I tried building, it incorrectly built "glad" and "utils" as .dll instead of .lib, which was required to link the test executables, so building the test executables failed. This could be fixed by manually changing the VS settings to build .lib out of glad and utils, but it would be nice to get the build config fixed.

**Comment by Kangz** [comment]
Fixed in @kkinnunen's PR.
